### ISSUE TITLE
从可乐鸡过来的

### ISSUE THREAD

**Issue by shuiyue036** [xiaoshanw/DNF-Limit#6]
先star以表尊敬，后续会持续更新体验已经意见反馈

**Comment by ddknight** [comment]
这种issue就不要开放了.点赞即可.建议关闭

**Comment by xiaoshanw** [comment]
> 
> 
> 这种issue就不要开放了.点赞即可.建议关闭

其实没什么，开源是最好的自证，我没有干坏事
